version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_projectmanager
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  eureka-server:
    image: augustaklug/eureka-server:latest
    ports:
      - "8761:8761"
    depends_on:
      - mysql
      - rabbitmq
      - zipkin

  backend:
    image: augustaklug/backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_projectmanager?createDatabaseIfNotExist=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=2e6a98abb5b23339ad14601d32e6a98abb5b23339ad14601d32e6a98abb5b23339ad14601d32e6a98abb5b23339ad14601d3
      - JWT_EXPIRY=3600000
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - eureka-server
      - mysql
      - rabbitmq
      - zipkin

  note-service:
    image: augustaklug/note-service:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_noteservice?createDatabaseIfNotExist=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - eureka-server
      - mysql
      - rabbitmq
      - zipkin

  frontend:
    image: augustaklug/frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://146.235.58.207:8080/api
    depends_on:
      - backend
      - note-service

volumes:
  mysql_data:
