apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: augustaklug/backend:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/db_projectmanager?createDatabaseIfNotExist=true"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  JWT_EXPIRY: "3600000"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  jwt-secret: MmU2YTk4YWJiNWIyMzMzOWFkMTQ2MDFkMzJlNmE5OGFiYjViMjMzMzlhZDE0NjAxZDMyZTZhOThhYmI1YjIzMzM5YWQxNDYwMWQzMmU2YTk4YWJiNWIyMzMzOWFkMTQ2MDFkMw==