apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-manager-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /api/backend
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /api/notes
            pathType: Prefix
            backend:
              service:
                name: note-service
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000