apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-service
  template:
    metadata:
      labels:
        app: note-service
    spec:
      containers:
      - name: note-service
        image: augustaklug/note-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/db_noteservice?createDatabaseIfNotExist=true"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: note-service
spec:
  selector:
    app: note-service
  ports:
    - port: 8081
      targetPort: 8081