apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-service
  template:
    metadata:
      labels:
        app: note-service
    spec:
      containers:
      - name: note-service
        image: augustaklug/note-service:latest
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: note-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: note-service
spec:
  selector:
    app: note-service
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: note-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/db_noteservice?createDatabaseIfNotExist=true"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"