name: Deploy to Oracle Cloud

on:
  workflow_run:
    workflows: ["Push to Docker Hub"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Install Oracle Cloud CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh > install-oci-cli.sh
          chmod +x install-oci-cli.sh
          ./install-oci-cli.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/home/runner/lib" >> $GITHUB_ENV
          source ~/.bashrc

      - name: Configure Oracle Cloud CLI
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        run: |
          mkdir -p ~/.oci
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${OCI_CLI_USER}" >> ~/.oci/config
          echo "tenancy=${OCI_CLI_TENANCY}" >> ~/.oci/config
          echo "fingerprint=${OCI_CLI_FINGERPRINT}" >> ~/.oci/config
          echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
          echo "region=${OCI_CLI_REGION}" >> ~/.oci/config
          echo "${OCI_CLI_KEY_CONTENT}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/config
          
      - name: Deploy to Oracle Cloud
        env:
          INSTANCE_OCID: ${{ secrets.INSTANCE_OCID }}
          ORACLE_SSH_PRIVATE_KEY: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          REPO_URL: ${{ secrets.REPO_URL }}
        run: |
          INSTANCE_IP=$(oci compute instance list-vnics --instance-id ${INSTANCE_OCID} --query 'data[0]."public-ip"' --raw-output)
          
          echo "$ORACLE_SSH_PRIVATE_KEY" > oracle_ssh_key
          chmod 600 oracle_ssh_key
          
          ssh -i oracle_ssh_key -o StrictHostKeyChecking=no ubuntu@${INSTANCE_IP} << EOF
            mkdir -p /home/ubuntu/meu-projeto
            cd /home/ubuntu/meu-projeto
            
            if [ -d ".git" ]; then
              git pull origin master
            else
              git clone ${REPO_URL} .
            fi
            
            if ! command -v docker &> /dev/null || ! command -v docker-compose &> /dev/null; then
              echo "Instalando Docker e Docker Compose..."
              sudo apt-get update
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              sudo usermod -aG docker $USER
            fi
            
            echo "Versão do Docker Compose:"
            docker-compose --version
            
            echo "Parando os contêineres existentes..."
            docker-compose down
            
            echo "Puxando as novas imagens..."
            docker-compose pull
            
            echo "Iniciando os serviços..."
            docker-compose up -d
            
            echo "Logs dos contêineres:"
            docker-compose logs
          EOF
