name: Deploy to Oracle Cloud

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Install Oracle Cloud CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh > install-oci-cli.sh
          chmod +x install-oci-cli.sh
          ./install-oci-cli.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/home/runner/lib" >> $GITHUB_ENV
          source ~/.bashrc

      - name: Configure Oracle Cloud CLI
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        run: |
          mkdir -p ~/.oci
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${OCI_CLI_USER}" >> ~/.oci/config
          echo "tenancy=${OCI_CLI_TENANCY}" >> ~/.oci/config
          echo "fingerprint=${OCI_CLI_FINGERPRINT}" >> ~/.oci/config
          echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
          echo "region=${OCI_CLI_REGION}" >> ~/.oci/config
          echo "${OCI_CLI_KEY_CONTENT}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem

      - name: Deploy to Oracle Cloud
        env:
          INSTANCE_OCID: ${{ secrets.INSTANCE_OCID }}
          ORACLE_SSH_PRIVATE_KEY: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
        run: |
          # Verificar a instalação do OCI CLI
          which oci
          oci --version
          
          # Obtenha o IP público da instância
          INSTANCE_IP=$(oci compute instance list-vnics --instance-id ${INSTANCE_OCID} --query "data[0].public-ip" --raw-output)
          
          # Configurar a chave SSH
          echo "${ORACLE_SSH_PRIVATE_KEY}" > oracle_ssh_key
          chmod 600 oracle_ssh_key
          
          # Deploy usando SSH
          ssh -i oracle_ssh_key -o StrictHostKeyChecking=no ubuntu@${INSTANCE_IP} << EOF
            cd /meu-projeto
            git pull origin master
            docker-compose pull
            docker-compose up -d --build
          EOF
